[package]
name = "srs_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
noir_rs = { git = "https://github.com/zkpassport/noir_rs.git", branch = "v1.0.0-beta.3", features = ["barretenberg"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
